name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.12.0
      id: review

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.12.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
