name: My CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install pip
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip -y
      
    - name: Install Python packages
      run: |
        pip3 install -r requirements.txt

    - name: Run cpplint
      run: |
        cpplint.sh
