name: cpplint

on: push

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install cpplint
      run: |
        sudo apt-get update
        sudo apt-get install -y python-pip
        pip install cpplint
    - name: Run cpplint
      run: |
        bash cpplint.sh
